### ISSUE TITLE
Fix custom dysplay for TODO admonitions

### ISSUE THREAD

**Issue by riazaia** [BobaBoard/boba-docs#56]
Instead of adding TODOs in our docs with comments we use an admonition is the following format:

```md
:::TODO
Text
:::
```

This currently displays the same as admonitions of the type `info`, but we want it to be distinct.

**Comment by enigmalea** [comment]
I may have tracked down the issue but I'm not sure how to fix it. When I did the build to get all the dead links for the Volunteers Tab reorg I got this:
![image](https://github.com/BobaBoard/boba-docs/assets/73132777/f9fd0128-0004-465b-9e87-8ddd4a75dd61)

[From the Docusaurus docs](https://docusaurus.io/docs/markdown-features/admonitions#customizing-admonitions) it looks like they might have changed how these are done? I couldn't find an `Admonitions.js` in the codebase.

@essential-randomness do you remember how you did these the first time?

**Comment by essential-randomness** [comment]
I think they have changed how they do it now, so we need to swizzle Admonitions. See: https://docusaurus.io/docs/markdown-features/admonitions#customizing-admonitions
